import Head from "next/head";
import { Roboto } from "next/font/google";
import MuiTypography from "@/components/MuiTypography";
import MuiButtons from "@/components/MuiButtons";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={roboto.className}>
        {/* <MuiTypography /> */}
        <MuiButtons />
      </main>
    </>
  );
}
